"""create_chat_messages_table

Revision ID: 42967f29e711
Revises: 7305e176186f
Create Date: 2026-06-13 11:04:30.085274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.infrastructure.models
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.types import Text


# revision identifiers, used by Alembic.
revision: str = '42967f29e711'
down_revision: Union[str, Sequence[str], None] = '7305e176186f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', src.infrastructure.models.GUID(), nullable=False),
    sa.Column('session_id', src.infrastructure.models.GUID(), nullable=False),
    sa.Column('sender_participant_id', src.infrastructure.models.GUID(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('metadata', src.infrastructure.models.SafeJSON(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['sender_participant_id'], ['participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_messages_session_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
