"""initial_schema

Revision ID: 7305e176186f
Revises: 
Create Date: 2026-06-13 10:37:28.253107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.infrastructure.models


# revision identifiers, used by Alembic.
revision: str = '7305e176186f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', src.infrastructure.models.GUID(), nullable=False),
    sa.Column('invite_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_invite_token'), 'sessions', ['invite_token'], unique=True)
    op.create_table('participants',
    sa.Column('id', src.infrastructure.models.GUID(), nullable=False),
    sa.Column('session_id', src.infrastructure.models.GUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_participants_session_id', 'participants', ['session_id'], unique=False)
    op.create_index('idx_participants_session_role', 'participants', ['session_id', 'role'], unique=True)
    op.create_table('session_events',
    sa.Column('id', src.infrastructure.models.GUID(), nullable=False),
    sa.Column('session_id', src.infrastructure.models.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('metadata', src.infrastructure.models.SafeJSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_events_session_id_timestamp', 'session_events', ['session_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_events_session_id_timestamp', table_name='session_events')
    op.drop_table('session_events')
    op.drop_index('idx_participants_session_role', table_name='participants')
    op.drop_index('idx_participants_session_id', table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_sessions_invite_token'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
